import React from "react";
// no need of adding images here because we already took them in the product.jsx
const Products_obj = [
  {
    // image: { ghee },
    url: "./A2ghee",
    heading: "Desi Ghee",
    p: "Best A2 desi ghee",
    category: "food",
  },
  {
    // image: "./images/indi-products/noodles/milletlife1.jpg",
    url: "./Noodles",
    heading: "Noodles",
    p: "Best Noodles",
    category: "food",
  },
  {
    // image: { pee },
    url: "./Hairoil",
    heading: "Hair-oil",
    p: "Best natural Hair-oil",
    category: "beauty",
  },
  {
    // image: "images/products/toothpaste.jpg",
    url: "./Paste",
    heading: "Paste",
    p: "Best natural Paste",
    category: "beauty",
  },
  {
    // image: "images/products/moisturizer.png",
    url: "./Facemoisturiser",
    heading: "Moisturizer",
    p: "Best natural Moisturizer",
    category: "beauty",
  },
  {
    // image: "images/products/chocolete.png",
    url: "./Chocolete",
    heading: "Chocolete",
    p: "Best chocolete",
    category: "food",
  },
  {
    // image: "images/products/butter.jpg",
    url: "./Butter",
    heading: "Butter",
    p: "Best natural Butter",
    category: "food",
  },
  {
    // image: "images/products/tea.jpg",
    url: "./Tea",
    heading: "Tea",
    p: "Best natural Tea",
    category: "food",
  },
  {
    // image: "images/products/water.png",
    url: "./Water",
    heading: "Water",
    p: "Best natural Water",
    category: "food",
  },
  {
    // image: "images/products/popcorn.jpg",
    url: "./Snacks",
    heading: "Snacks",
    p: "Best healthy Snacks",
    category: "food",
  },
  {
    // image: "images/products/cold_drink.png",
    url: "./Colddrink",
    heading: "Cold-drink",
    p: "Best healthy Cold-drink",
    category: "food",
  },
  {
    // image: "images/products/biscuit.jpg",
    url: "./Biscuits",
    heading: "Biscuits",
    p: "Best healthy Biscuits",
    category: "food",
  },
  {
    // image: "images/products/bath_soap.jpg",
    url: "./Soap",
    heading: "Bath-soap",
    p: "Best natural Bath-soap",
    category: "beauty",
  },
  {
    // image: "images/products/shampoo.png",
    url: "./Shampoo",
    heading: "Shampoo",
    p: "Best natural Shampoo",
    category: "beauty",
  },
  {
    // image: "images/products/essential_oil.jpg",
    url: "./Essentialoil",
    heading: "Essential-oil",
    p: "Best natural Essential-oil",
    category: "beauty",
  },
  {
    // image: "images/products/hand_wash.jpg",
    url: "./Handwash",
    heading: "Hand-wash",
    p: "Best natural Hand-wash",
    category: "beauty",
  },
  // {
  // image: "images/products/ghee.jpg",
  //   url: "./Ghee",
  //   heading: "Ghee",
  //   p: "Best A1 Ghee",
  //   category: "food",
  // },
  // {
  //   image: "images/products/honey.jpg",
  //   url: "./Ghee",
  //   heading: "Honey",
  //   p: "Best natural Honey",
  //   category: "food",
  // },

  // {
  //   image: "images/products/milk.jpg",
  //   url: "./Ghee",
  //   heading: "Milk",
  //   p: "Best natural Milk",
  //   category: "food",
  // },
  // {
  //   image: "images/products/flour.jpg",
  //   url: "./Ghee",
  //   heading: "Flour",
  //   p: "Best natural Flour",
  //   category: "food",
  // },
  // {
  //   image: "images/products/oats.jpg",
  //   url: "./Ghee",
  //   heading: "Oats",
  //   p: "Best natural Oats",
  //   category: "food",
  // },
  // {
  //   image: "images/products/oil.jpg",
  //   url: "./Ghee",
  //   heading: "Oil",
  //   p: "Best natural Oil",
  //   category: "food",
  // },
  // {
  //   image: "images/products/soup.jpg",
  //   url: "./Soup",
  //   heading: "Soup",
  //   p: "Best natural Soup",
  //   category: "food",
  // },

  // {
  //   image: "images/products/hand_sanitizer.png",
  //   url: "./Ghee",
  //   heading: "Hand-sanitizer",
  //   p: "Best natural Hand-sanitizer",
  //   category: "beauty",
  // },

  // {
  //   image: "images/products/face_wash.png",
  //   url: "./Ghee",
  //   heading: "Face-wash",
  //   p: "Best natural Face-wash",
  //   category: "beauty",
  // },
  // {
  //   image: "images/products/face_scrub.png",
  //   url: "./Ghee",
  //   heading: "Face-scrub",
  //   p: "Best natural Face-scrub",
  //   category: "beauty",
  // },
  // {
  //   image: "images/products/phone.png",
  //   url: "./Ghee",
  //   heading: "Mobiles",
  //   p: "Best Mobiles",
  //   category: "electronics",
  // },
  // {
  //   image: "images/products/laptop.jpg",
  //   url: "./Ghee",
  //   heading: "Laptops",
  //   p: "Best Laptops",
  //   category: "electronics",
  // },
];
export default Products_obj;
